server:
    port: 8080
spring:
    application:
        name: restaurant
    datasource:
        druid:
            driver-class-name:  com.mysql.cj.jdbc.Driver
            url: jdbc:mysql://localhost:3306/restaurant
            username: root
            password: root
mybatis-plus:
    configuration:
        # map db(name with underscore) to java bean(camel case)
        map-underscore-to-camel-case: true
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
global-config:
    db-config:
        id-type: ASSIGN_ID

